version: '3.8'

services:
  microservice_a:
    build:
      context: ./servicoA
    container_name: microservicoA
    ports:
      - "8001:8000"   
    networks:
      - desafio4_net

  microservice_b:
    build:
      context: ./servicoB
    container_name: microservicoB
    ports:
      - "8000:8000"   
    networks:
      - desafio4_net

networks:
  desafio4_net:
    driver: bridge
